# Generated by Django 3.0.5 on 2020-04-15 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='tweeted',
            field=models.ManyToManyField(related_name='tweeted', to='core.Tweet'),
        ),
    ]
