# Generated by Django 3.0.5 on 2020-04-15 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200414_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='textpair',
            name='belongTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tweet'),
        ),
    ]
