# Generated by Django 3.0.5 on 2020-04-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_textpair_belongto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='id',
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
