# Generated by Django 3.0.5 on 2020-04-15 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200415_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='tweets',
            field=models.ManyToManyField(related_name='tweeted', to='core.Tweet'),
        ),
    ]
