# Generated by Django 3.0.5 on 2020-04-15 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200415_0102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='tweets',
            new_name='tweeted',
        ),
    ]
